# Generated by Django 4.2.19 on 2025-05-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
