# Generated by Django 4.2.19 on 2025-05-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_rename_books_orderitems_book_alter_orderitems_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='book',
            new_name='product',
        ),
    ]
