# Generated by Django 4.2.19 on 2025-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='P Diddy', max_length=100),
        ),
    ]
