# Generated by Django 4.2.19 on 2025-05-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_app.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_app.order')),
            ],
        ),
    ]
