# Generated by Django 4.2.19 on 2025-05-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='books',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shop_app.order'),
        ),
    ]
