# Generated by Django 4.2.19 on 2025-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='someting',
            field=models.IntegerField(default=5),
        ),
    ]
