# Generated by Django 4.2.19 on 2025-08-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_book_someting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='someting',
        ),
    ]
